// Mocks generated by Mockito 5.4.4 from annotations
// in fl_mvvm/test/fl_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:fl_mvvm/src/fl_state.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:signals_flutter/signals_flutter.dart' as _i2;

import 'fl_view_test.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignal_0<T> extends _i1.SmartFake implements _i2.Signal<T> {
  _FakeSignal_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TestViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestViewModel extends _i1.Mock implements _i3.TestViewModel {
  @override
  bool get autoDispose => (super.noSuchMethod(
        Invocation.getter(#autoDispose),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitilized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.Signal<_i4.FlState<String>> get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _FakeSignal_0<_i4.FlState<String>>(
          this,
          Invocation.getter(#state),
        ),
        returnValueForMissingStub: _FakeSignal_0<_i4.FlState<String>>(
          this,
          Invocation.getter(#state),
        ),
      ) as _i2.Signal<_i4.FlState<String>>);

  @override
  bool get isLoadng => (super.noSuchMethod(
        Invocation.getter(#isLoadng),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isError => (super.noSuchMethod(
        Invocation.getter(#isError),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isData => (super.noSuchMethod(
        Invocation.getter(#isData),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isDisposed => (super.noSuchMethod(
        Invocation.getter(#isDisposed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void buildDependencies() => super.noSuchMethod(
        Invocation.method(
          #buildDependencies,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onViewInitialized() => super.noSuchMethod(
        Invocation.method(
          #onViewInitialized,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onDispose() => super.noSuchMethod(
        Invocation.method(
          #onDispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setState(_i4.FlState<String>? newState) => super.noSuchMethod(
        Invocation.method(
          #setState,
          [newState],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLoading() => super.noSuchMethod(
        Invocation.method(
          #setLoading,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setData(String? data) => super.noSuchMethod(
        Invocation.method(
          #setData,
          [data],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setFutureData(
    _i5.Future<String?>? futureData, {
    bool? withLoading = true,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setFutureData,
          [futureData],
          {#withLoading: withLoading},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setEmpty([String? message = r'']) => super.noSuchMethod(
        Invocation.method(
          #setEmpty,
          [message],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setError(
    Object? error, [
    StackTrace? stackTrace,
  ]) =>
      super.noSuchMethod(
        Invocation.method(
          #setError,
          [
            error,
            stackTrace,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i4.FlState<String>?>
      waitForStateChange<S extends _i4.FlState<dynamic>>({int? timeout}) =>
          (super.noSuchMethod(
            Invocation.method(
              #waitForStateChange,
              [],
              {#timeout: timeout},
            ),
            returnValue: _i5.Future<_i4.FlState<String>?>.value(),
            returnValueForMissingStub: _i5.Future<_i4.FlState<String>?>.value(),
          ) as _i5.Future<_i4.FlState<String>?>);
}
